CXX=cl
CXXFLAGS=-std:c++17 /O2 /Oi /MD -DNDEBUG

all: conll2vec.exe

conll2vec.exe: 
	if exist $@ del $@
	cl /nologo /c /EHsc /Fosrc\ $(CXXFLAGS) src/conll2vec.cpp
	link /nologo /SUBSYSTEM:CONSOLE /OUT:$@ src/conll2vec.obj

clean:
	-if exist src\*.obj del src\*.obj
	-if exist conll2vec.exe del conll2vec.exe

